version: '3.9'
services:
    umbraco9-web:
        build: '.'
        ports:
            - '8809:80'
    umbraco9-db:
        build: './DB'
        ports:
            - '3930:1433'
            - '3931:1434'
        